[supervisord]
nodaemon=true

[program:asktao_1]
command=/app/data/starts/start1.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/1_stdout.log
stderr_logfile=/app/logs/1_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_gs]
command=/app/data/starts/startgs.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/gs_stdout.log
stderr_logfile=/app/logs/gs_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
