[supervisord]
nodaemon=true          ; 前台运行，不要放后台，否则 Docker 退出

[program:asktao_1]
command=/home/asktao/starts/start1.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/1/stdout.log
stderr_logfile=/home/asktao/logs/1/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_aaa]
command=/home/asktao/starts/startaaa.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/aaa/stdout.log
stderr_logfile=/home/asktao/logs/aaa/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_dba]
command=/home/asktao/starts/startdba.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/dba/stdout.log
stderr_logfile=/home/asktao/logs/dba/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_ccs]
command=/home/asktao/starts/startccs.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/ccs/stdout.log
stderr_logfile=/home/asktao/logs/ccs/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_csa]
command=/home/asktao/starts/startcsa.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/csa/stdout.log
stderr_logfile=/home/asktao/logs/csa/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_gs]
command=/home/asktao/starts/startgs.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/home/asktao/logs/gs/stdout.log
stderr_logfile=/home/asktao/logs/gs/error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB