[supervisord]
nodaemon=true

[program:asktao_1]
command=/app/data/starts/start1.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/1_stdout.log
stderr_logfile=/app/logs/1_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_aaa]
command=/app/data/starts/startaaa.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/aaa_stdout.log
stderr_logfile=/app/logs/aaa_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_dba]
command=/app/data/starts/startdba.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/dba_stdout.log
stderr_logfile=/app/logs/dba_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_ccs]
command=/app/data/starts/startccs.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/ccs_stdout.log
stderr_logfile=/app/logs/ccs_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:asktao_csa]
command=/app/data/starts/startcsa.sh
autostart=true
autorestart=unexpected
startretries=0
stdout_logfile=/app/logs/csa_stdout.log
stderr_logfile=/app/logs/csa_error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB